apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-smrj
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0019-tenant/tkrw-pr712-0075-0019-app/devfile-sample-smrj@sha256:9c80d39730c3f14cfdf8d286ed1b74b1892ca043ee6b1c993acd7b84781469bf
        name: my-nodejs
        resources: {}
status: {}
